### ISSUE TITLE
Results of the model

### ISSUE THREAD

**Issue by Lijiatu321** [JACKYLUO1991/CMNet#1]
作者您好，非常感谢您优秀的工作。我最近用您的代码复现了在ＤＲIVE数据集上面的结果，我发现我的实验结果和论文中的结果有一些出入，就ＡＵC这个指标来说，我的实验结果是０．９４７６，我想请教一下怎样才能达到论文中的效果，谢谢

**Comment by JACKYLUO1991** [comment]
鉴于论文目前还在under review阶段，目前暂时不方便公开实验调参过程及预训练模型 谢谢理解…



---Original---

**Comment by Lijiatu321** [comment]
非常感谢，祝论文早中！

**Comment by JACKYLUO1991** [comment]
谢谢 论文被收录后 我将第一时间公开详细流程及预训练模型 感谢支持



---Original---
